# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: pvent

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

# Check https://goreleaser.com/customization/homebrew/
brews:
  - name: pvent
    homepage: "https://github.com/dotunj/pvent"
    description: "Send Events to different Message brokers"
    commit_author:
      name: dotunj
      email: dotunjolaosho@gmail.com
    tap:
      owner: dotunj
      name: homebrew-tools
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
