name: Release Go Binaries

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual Workflow name"
        required: true

  push:
    tags:
      - v*

jobs:
  release:
    name: Release & Publish Go Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
        with: 
          fetch-depth: 0
          
      - uses: actions/setup-go@v2
        name: Setup Go
        with:
          go-version: 1.19

      - uses: goreleaser/goreleaser-action@v2
        name: Release, Upload & Publish
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}